autoslider/boards/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt

app_name = 'boards'

urlpatterns = [
    path('list/', views.BoardListView.as_view(), name='board_list'),  # board_list 기본 & 목록
    path('favorite/', views.FavoriteBoardListView.as_view(), name='favorite_board_list'),
    path('new/', views.BoardCreateView.as_view(), name='board_create'),
    path('<int:pk>/', views.BoardDetailView.as_view(), name='board_detail'),
    path('<int:pk>/modifav', views.modifiy_favorite, name='modifiy_favorite'),
    # path('<int:pk>/update/', views.BoardUpdateView.as_view(), name='board_update'),
    # path('<int:pk>/delete/', views.BoardDeleteView.as_view(), name='board_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#  MEDIA_URL로 접근하면 MEDIA_ROOT 경로에 저장된 파일을 서비스하도록 설정함. 이제 파일 업로드 뷰에서 파일을 업로드하면 MEDIA_ROOT에 파일이 저장되고, 데이터베이스에는 파일 경로가 저장됨.

handler403 = 'django.views.defaults.permission_denied'
handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'

autoslider/config/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls', 'common')), # '/' 에 해당되는 path
    path('', include('boards.urls', 'boards')),
]

# from django.contrib import admin
# from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static
# from django.views.generic.base import TemplateView
# from common import views

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     # path('', views.IndexView.as_view(), name='index'),  # '/' 에 해당되는 path
#     # path('common/', include(('common.urls', 'common'))),
#     # path('common/', include('django.contrib.auth.urls')),
#     # path('care/', include('care.urls')), # 요양원&리뷰
#     path('', include(('common.urls', 'common'))),
#     path('common/', include('django.contrib.auth.urls')),
#     path('care/', include('care.urls')), # 요양원&리뷰
#     path('care/', include('django.contrib.auth.urls')),
# ]

autoslider/boards/models.py
from django.db import models
from django.utils import timezone
from common.models import CustomUser

# Create your models here.

class Board(models.Model):
    input_type_choices = [
        ('input_text', '텍스트 요약'),
        ('input_youtube', 'Youtube 영상 링크 입력'),
        ('input_video', '영상 파일 업로드')
    ]
    title = models.TextField(blank=True)
    input_type = models.TextField(choices=input_type_choices, null=True)
    input_text = models.TextField(blank=True, null=True)
    input_youtube = models.TextField(blank=True, null=True)
    input_video = models.FileField(upload_to='videos/', blank=True, null=True)
    total_text = models.TextField(blank=True, null=True)
    summary_text = models.TextField(blank=True, null=True)
    timeline_text = models.TextField(blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    favorite = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if (not self.title.strip()) or (self.title == "") or (self.title is None) : # 제목이 없는 경우에만 생성 날짜를 저장
            now = timezone.now()
            formatted_time = now.strftime('%Y-%m-%d %H:%M')
            self.title = formatted_time # str(self.created_at)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'id={self.id} / user = {self.user_id.username} : {self.title}'

autoslider/boards/forms.py
from django import forms
from .models import Board

class BoardCreateForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['input_type', 'input_text', 'input_youtube', 'input_video', ] # 'title', 'note', 'favorite', 'total_text', 'summary_text', 'timeline_text',
        widgets = {
            # base.html
            'input_type': forms.Select(choices=Board.input_type_choices, attrs={'class': 'input_type'}),
            'input_text': forms.Textarea(attrs={'id': 'input_text'}),
            'input_youtube': forms.TextInput(attrs={'id': 'input_youtube'}),
            'input_video': forms.ClearableFileInput(attrs={'id': 'input_video'}),
            # 'title': forms.TextInput(attrs={'class': 'form-control'}),
            # 'total_text': forms.Textarea(attrs={'class': 'form-control'}), # , 'rows': 5
            # 'summary_text': forms.Textarea(attrs={'class': 'form-control'}),
            # 'timeline_text': forms.Textarea(attrs={'class': 'form-control'}),
            # 'note': forms.Textarea(attrs={'class': 'form-control'}),
        }

class BoardNoteForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['note']
        widgets = {
            'note': forms.Textarea(attrs={'id': 'user_note'}),
        }

autoslider/boards/views.py
# from django.contrib.auth import get_user_model, login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, View
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseRedirect
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings

from django.db.models import Q

from .models import Board
from .forms import BoardCreateForm, BoardNoteForm

import os
import json
import torch
import whisper
import pytube
from pytube import YouTube
from pydub import AudioSegment
from moviepy.editor import *
from transformers import PreTrainedTokenizerFast, BartForConditionalGeneration

# error log
import logging
logger = logging.getLogger(__name__)

def my_view(request):
    logger.info('boards/views.py Log start!')


# Create your views here.

# BoardListView
# 모든 보드 목록
class BoardListView(LoginRequiredMixin, ListView):  # LoginRequiredMixin을 상속받아 로그인한 사용자만 접근할 수 있도록 설정
    model = Board
    template_name = 'boards/board_list.html'
    paginate_by = 10

    def get_queryset(self):
        # Filter the queryset to include only boards created by the current user
        # return Board.objects.filter(user_id=self.request.user.id)
        query = self.request.GET.get('q')
        if query:
            return Board.objects.filter(
                Q(title__icontains=query) | Q(note__icontains=query) | Q(total_text__icontains=query) | Q(summary_text__icontains=query),
                user_id=self.request.user.id
            )
        else:
            return Board.objects.filter(user_id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['board_list'] = self.get_queryset()
        return context


# 즐겨찾기 인 경우 override함.
class FavoriteBoardListView(BoardListView):
    def get_queryset(self):
        queryset = super().get_queryset().filter(favorite=True)
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) | Q(note__icontains=query) | Q(total_text__icontains=query) | Q(summary_text__icontains=query)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['favorite_board_list'] = self.get_queryset()
        return context



# 즐겨찾기 추가/삭제
def modifiy_favorite(request, pk):
    board = get_object_or_404(Board, pk=pk)
    board.favorite = not board.favorite
    board.save()
    response_data = {'favorite': board.favorite}

    if request.method == 'POST':
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            return JsonResponse(response_data)
    return HttpResponseRedirect(reverse('boards:board_detail', args=[pk]))



# 상세 보드
class BoardDetailView(LoginRequiredMixin, DetailView):
    model = Board
    template_name = 'boards/board_detail.html'
    form_class = BoardNoteForm  # BoardCreateForm
    # success_url = reverse_lazy('board_detail')

    # 로그인한 사용자와 요약 작성자가 일치하지 않으면 에러 페이지 반환
    def get_object(self, queryset=None):
        obj = get_object_or_404(Board, id=self.kwargs['pk'])
        if obj.user_id != self.request.user:
            raise HttpResponseForbidden("You are not allowed to view this summary.")
        return obj

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('boards:board_detail', kwargs={'pk': self.object.pk})


# 보드 삭제
class BoardDeleteView(LoginRequiredMixin, View):
    def post(self, request):
        if 'board_ids' in request.POST:
            board_ids = request.POST.get('board_ids').split('-')
            Board.objects.filter(id__in=board_ids).delete()
        return redirect('boards:board_list')



# 영상 업로드 & youtube 다운 & 긴 텍스트 요약 처리

# chocolatey 로 ffmpge 설치 했으나 경로 지정 필요
def get_ffmpeg_path():
    search_paths = [
        r'C:\Program Files\ffmpeg\bin',
        r'C:\Program Files (x86)\ffmpeg\bin',
        r'C:\ProgramData\chocolatey\bin',
    ]

    for path in search_paths:
        ffmpeg_path = os.path.join(path, 'ffmpeg.exe')
        if os.path.exists(ffmpeg_path):
            return ffmpeg_path

    return None

ffmpeg_path = get_ffmpeg_path()
if ffmpeg_path:
    os.environ["PATH"] = ffmpeg_path + os.pathsep + os.environ["PATH"]
    os.environ["FFMPEG_BINARY"] = ffmpeg_path # FFmpeg 경로 설정
    AudioSegment.ffmpeg = ffmpeg_path  # pydub 패키지가 ffmpeg.exe 경로를 인식하도록 함.
else:
    print("FFmpeg not found in any search path")


tokenizer = PreTrainedTokenizerFast.from_pretrained('digit82/kobart-summarization')
model = BartForConditionalGeneration.from_pretrained('digit82/kobart-summarization')


# 텍스트 분리
def split_text(text, max_length):
    words = text.split()
    parts = []
    current_part = []

    for word in words:
        current_part.append(word)
        if len(tokenizer.encode(" ".join(current_part))) > max_length:
            current_part.pop()
            parts.append(" ".join(current_part))
            current_part = [word]

    if current_part:
        parts.append(" ".join(current_part))

    return parts


# 텍스트 요약
def summarize(text):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    input_ids = tokenizer.encode(text)
    input_ids = torch.tensor(input_ids).unsqueeze(0).to(device)

    output = model.generate(input_ids, eos_token_id=1, max_length=512, num_beams=5, no_repeat_ngram_size=1)
    return tokenizer.decode(output[0], skip_special_tokens=True)


# 전문 텍스트 요약
def summarize_long_text(text):
    max_input_length = 1000  # 몇 개의 여유 토큰을 남겨두기 위해 1026보다 작은 값을 사용합니다.
    text_parts = split_text(text, max_input_length)

    summarized_parts = []
    for part in text_parts:
        summary = summarize(part)
        summarized_parts.append(summary)

    return " ".join(summarized_parts)


# timestamp track -> timeline 생성
def create_timelined_text(segments):
    timelined_text = []
    for segment in segments:
        segment_start = round(segment['start'], 2)
        segment_text = segment['text']
        segment_t = round(segment_start, 2)
        segment_text_with_t = f'<span t="{segment_t}" data-lexical-text="true" style="" onclick="seekToTimestamp(\'{segment_t}\');">{segment_text}</span>'
        timelined_text.append(segment_text_with_t)
    return "\n".join(timelined_text)


import re
def youtube_url_validation(url):
    youtube_regex = (
        r'(https?://)?(www\.)?'
        '(youtube|youtu|youtube-nocookie)\.(com|be)/'
        '(watch\?v=|embed/|v/|.+\?v=)?([^&=%\?]{11})')

    youtube_regex_match = re.findall(youtube_regex, url)
    if youtube_regex_match:
        return youtube_regex_match[0][-1]


# 요약 종합
class BoardCreateView(LoginRequiredMixin, CreateView):
    def post(self, request):
        form = BoardCreateForm(request.POST, request.FILES)
        if form.is_valid():
            board = form.save(commit=False)
            form.instance.user_id = self.request.user

            # Handle text summary
            input_text = form.cleaned_data['input_text']
            if input_text:
                # Use a function to summarize long text
                # summary_text = summarize_long_text(input_text)
                # timeline_text = ""
                board.total_text = input_text
                board.summary_text = summarize_long_text(input_text)
                board.timeline_text = ""
                board.save()
                # Define the URL to redirect to
                redirect_url = reverse('boards:board_detail', args=[board.id])
                return redirect(redirect_url)

            # Handle YouTube links
            input_youtube = form.cleaned_data['input_youtube']
            if input_youtube:

                # 동영상 다운로드를 위한 경로 설정
                VIDEO_DIR = os.path.join(settings.MEDIA_ROOT, 'youtube/')
                if not os.path.exists(VIDEO_DIR):
                    os.mkdir(VIDEO_DIR)

                # 다운로드할 동영상의 URL
                youtube = pytube.YouTube(input_youtube)

                # 비디오 다운로드
                video = youtube.streams.filter(file_extension='mp4').first()
                # only_audio=True, -> 음성만
                video.download(output_path=VIDEO_DIR) #  filename=f'audio_

                # Run deep learning model
                device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
                whispermodel = whisper.load_model("small", device=device) # medium

                result = whispermodel.transcribe(os.path.join(VIDEO_DIR,video.default_filename))
                original_text = result["text"]
                segments = result["segments"]
                # Board 인스턴스에 저장.
                board.title = youtube.title
                board.total_text = result["text"]
                board.summary_text = summarize_long_text(original_text)
                board.timeline_text = create_timelined_text(segments)
                board.total_text = original_text

                board.save()

                os.remove(os.path.join(VIDEO_DIR,video.default_filename))
                redirect_url = reverse('boards:board_detail', args=[board.id])
                return redirect(redirect_url)

        # Video file processing
            input_video = form.cleaned_data['input_video']
            if input_video:
                # 파일 업로드가 있는 경우
                file_name = default_storage.save(input_video.name, ContentFile(input_video.read()))
                file_path = default_storage.path(file_name)

                #whisper로 자막화 하는 코드
                device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

autoslider/templates/boards/board_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    
</style>
<section class="board_detail {{ object.input_type }}">
    <div class="toparea">
        <h3 class="tit">{{ object.title }}</h3>
        <ul class="btnarea">
            <li><a href="#" class="btn btn-primary">스크랩 찾기</a></li>
            <li>
                <form method="post" action="{% url 'boards:modifiy_favorite' object.pk %}">
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <button type="submit" class="btn btn-primary">
                        {% if object.favorite %} 즐겨찾기 삭제 {% else %} 즐겨찾기 추가 {% endif%}
                    </button>
                </form>
            </li>
            <li><a href="#" class="btn btn-primary">저장하기</a></li>
            <li class="goback"><a href="{% url 'boards:board_list' %}">목록으로 돌아가기</a></li>
        </ul>
    </div>
    <div class="detail_content">
    {% if object.input_type == "input_text" %}
    <div class="input_text">
        <h4>{{ object.title }} 에 작성된 텍스트의 전문/요약문입니다.</h4>
        <div class="textSection wholeText">
            <div class="toggleBtn">
                <label class="switch">
                    <input type="checkbox" id="toggleText" />
                    <span class="slider round"></span>
                </label>
                <span class="opt total_text on">전문</span><span class="opt summary_text">요약문</span>
            </div>
            <div class="content"></div>
        </div>
    </div>
    {% elif object.input_type == "input_youtube" %}
    <div class="videos">
        <h4>{{ object.title }}</h4>
        <div id="player" class="videoSection"></div>
        <div class="textSection">
            <div class="toggleBtn">
                <label class="switch">
                    <input type="checkbox" id="toggleText" />
                    <span class="slider round"></span>
                </label>
                <span class="opt total_text on">전문</span><span class="opt summary_text">요약문</span>
            </div>
            <div class="content"></div>
        </div>
    </div>
    {% elif object.input_type == "input_video" %}
    <div class="videos">
        <h4>{{ object.title }}</h4>
        <p class="input_video">{{ object.input_video.url }}</p>
        <div id="player" class="videoSection">
            <video width="320" height="240" controls>
                <source src="{{ MEDIA_URL }}{{ object.input_video }}" type="video/mp4">
            </video>
        </div>
        <div class="textSection">
            <div class="toggleBtn">
                <label class="switch">
                    <input type="checkbox" id="toggleText" />
                    <span class="slider round"></span>
                </label>
                <span class="opt total_text on">전문</span><span class="opt summary_text">요약문</span>
            </div>
            <div class="content"></div>
        </div>
    </div>
    {% endif %}
    </div>
</section>
<!-- html iframe 으로 youtube video 삽입 -->
<script type="text/javascript">

    // text_input 에서 전문, 요약문 선택
    var check = $("#toggleText");
    check.on('click', (event) => {
        $(".opt").toggleClass("on");
        if ($(".total_text").hasClass("on")){
            $(".textSection .content").text("");
            $(".textSection .content").text("{{ object.total_text }}");
        } else{
            $(".textSection .content").text("");
            $(".textSection .content").text("{{ object.summary_text }}");
        }
    });

    // 유튜브 API를 비동기적으로 로드합니다.
    function youtubeUrlValidation(url) {
        const youtubeRegex = /(https?:\/\/)?(www\.)?(youtube|youtu|youtube-nocookie)\.(com|be)\/(watch\?v=|embed\/|v\/|.+\?v=)?([^&=%\?]{11})/;
        const youtubeRegexMatch = url.match(youtubeRegex);
        if (youtubeRegexMatch) { return youtubeRegexMatch[6]; }
        return null;
    }
    var video_id = youtubeUrlValidation("{{object.input_youtube}}");
    var tag = document.createElement('script');
    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    var player;
    var done = false;

    function stopVideo() {
        player.stopVideo();
    }
    function onPlayerReady(event) {
        event.target.playVideo();
    }
    function onPlayerStateChange(event){
        if (event.data === 0) { stopVideo() }
    }
    function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
        height: '325',
        width: '525',
        videoId: video_id,
        playerVars: {
        'playsinline': 1
        },
        events: {
            //'onReady': onPlayerReady,  // 새로고침 시 자동재생 안 되도록 주석 처리
            'onStateChange': onPlayerStateChange
        }
    });
    }
    //
    $(document).ready(function() {
        // text 에 기본적으로 전문 넣기
        $(".textSection .content").text('{{ object.total_text }}')

        

    });
</script>
{% comment %}
<script type="text/javascript" src="{% static 'js/VideoTrace.js' %}"></script>
{% endcomment %}
{% endblock %}

autoslider/templates/boards/board_list.html
{% extends "base.html" %}
{% block content %}
<!-- S: board_list.html --><!-- 해당 페이지는 login한 유저만 들어올 수 있도록 view에서 처리됨. -->
{% load static %}
{% include "navbar.html" %}
<section class="board_list container-fluid">
{% if  request.resolver_match.url_name == 'board_list' %}
  <h2>메인 보드</h2>
  <div class="searchSection">
    <form method="get" action="{% url 'boards:board_list' %}">
      <div class="form-group row">
        <div class="col btnarea">
          <button type="submit" class="btn btn-primary"><strong class="fa fa-search"><span class="modal hide">검색</span></strong></button>
        </div>
        <div class="col searcharea">
            <input type="text" name="q" class="form-control" placeholder="검색어를 입력하세요." value="{{ q }}">
        </div>
      </div>
    </form>
  </div>
  <div class="list_result">
    {% if board_list %}
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>
                <input type="checkbox" id="boards_all" name="board_ids" value="{{ board_list.all.0.id }}-{{ board_list.all.last.id }}"> <!-- 전체 선택 -->
                <label for="boards_all"><strong>생성일자</strong></label>
              </th>
              <th>
                <strong>보드 이름</strong>
              </th>
            </tr>
          </thead>
          <tbody>
          {% for board in board_list %}
            <tr>
              <td>
                <input type="checkbox" id="{{ board.id }}" name="board_ids" value="{{ board.id }}">
                <label for="{{ board.id }}">{{ board.created_at }}</label>
              </td>
              <td>
                <p class="board_tit">{{ board.title }}</p>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
      <p class="no_result">목록이 없습니다.</p>
    {% endif %}
  </div>
{% elif request.resolver_match.url_name == 'favorite_board_list' %}
  <h2>즐겨찾기</h2>
  <div class="searchSection">
    <form method="get" action="{% url 'boards:favorite_board_list' %}">
      <div class="form-group row">
        <div class="col btnarea">
          <button type="submit" class="btn btn-primary"><strong class="fa fa-search"><span class="modal hide">검색</span></strong></button>
        </div>
        <div class="col searcharea">
            <input type="text" name="q" class="form-control" placeholder="검색어를 입력하세요." value="{{ q }}">
        </div>
      </div>
    </form>
  </div>
  {% if favorite_board_list %}
  favorite_board_list 있음 : {{ favorite_board_list }}
    {% for board_fav in favorite_board_list %}
      {% if board_fav.favorite %}
      <h3>{{ board_fav.title }}</h3>
      <p>{{ board_fav.description }}</p>
      {% endif %}
    {% endfor %}
  {% else %}
  <p class="no_result">목록이 없습니다.</p>
  {% endif %}
{% endif %}
</section>
<footer class="footer bg-light">
  <div class="rows">
      <div class="rights">
          <p class="copyright">Copyright @ AutoSlider Since 2022</p>
      </div>
      <ul class="info">
          <li><strong>팀명 :</strong>팀_안드</li>
          <li><strong>서비스 문의 :</strong><a href="mailto:admin@autoslider.com" class="mailto">admin@autoslider.com</a></li>
      </ul>
      <ul class="links">
          <li><a class="btn btn-outline-light btn-floating m-1" href="https://github.com/AutoSlider/total" target="_blank" role="button"><img src="{% static '../../img/icons/png/github-mark.png' %}" alt="gitHub linke"></a></li>
          <li><a href="#" target="_blank"><a class="btn btn-outline-light btn-floating m-1" href="mailto:admin@autoslider.com" target="_blank" role="button"><img src="{% static '../../img/icons/png/email.png' %}" alt="mail"></a></li>
      </ul>
  </div>
</footer>
<!-- 새 보드 만들기 내부 팝업 -->
<div class="modal fade file-upload" id="newBoardModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content modal_popup">
        <div class="modal-header">
            <h4 class="modal-title hide">새 보드 만들기</h4>
            <button type="button" class="fa fa-close closeBtn" data-dismiss="modal" aria-hidden="true">
                <strong class="modal hide">닫기</strong>
            </button>
        </div>
        <form id="newBoardForm" method="post" action="{% url 'boards:board_create' %}" enctype="multipart/form-data">
          {% csrf_token %}
          {% include "form_errors.html" %}
          <div class="modal-body">
            <!-- select 태그 추가 -->
            <div class="select_type">
                <label for="selectInput">입력 방법에 대해 선택해 주세요.</label>
                <select id="selectInput" class="form-control input_type" name="input_type">
                  <option value="input_text">텍스트 요약</option>
                  <option value="input_youtube">Youtube 영상 링크 입력</option>
                  <option value="input_video">영상 파일 업로드</option>
                </select>
            </div>
            <div class="form-group input_text">
                <label for="input_text" class="modal">텍스트 요약:</label>
                <div class="inputarea">
                  <textarea class="form-control" id="input_text" name="input_text" placeholder="요약할 텍스트를 입력해주세요." cols="30" rows="10"></textarea>
                </div>
            </div>
            <div class="form-group input_youtube">
                <label for="input_youtube" class="modal hide">Youtube 영상 링크 입력:</label>
                <div class="inputarea">
                  <input type="text" class="form-control" id="input_youtube" name="input_youtube" placeholder="유튜브 링크 입력하기" onblur="validateYoutubeLink()" />
                </div>
                <strong class="youtube_validation_msg"></strong>
            </div>
            <div class="form-group input_video">
                <label for="input_video">
                  <span><strong class="fa fa-plus"></strong><p>내 파일을 클릭하세요</p><p>자신이 원하는 .mp4 혹은 .wav 영상을 추가하세요</p></span>
                  <p class="uploadchk"></p>
                </label>
                <div class="inputarea">
                  <input type="file" class="form-control-file" id="input_video" name="input_video" accept=".wav,.mp4,.mp3" />
                </div>
            </div>
          </div>
          <div class="modal-footer">
              <ul class="btnarea">
                  <li><button type="submit" class="btn btn-primary">적용하기</button></li>
                  <li><button type="button" class="btn btn-default closeBtn" data-dismiss="modal">취소</button></li>
              </ul>
          </div>
      </form>
    </div>
  </div>
</div>
<!-- # newBoard JavaScript -->
<script type="text/javascript" >
  // youtube link validator
  function validateYoutubeLink() {
    console.log("validateYoutubeLink raise");
    const youtubeInput = $("#input_youtube").val();
    const youtubeRegex = /^(https?:\/\/)?(www\.)?(youtube|youtu|youtube-nocookie)\.(com|be)\/(watch\?v=|embed\/|v\/|.+\?v=)?([^&=%\?]{11})/;
    // /^(http(s)?:\/\/)?((w){3}.)?youtu(be|.be)?(\.com)?\/.+$/;

    var css_conf = {
      "display":"block",
      "width": "100%",
      "padding": "10px",
      "font-weight": "bold"
    };
    $(".youtube_validation_msg").css(css_conf);
    if (youtubeRegex.test(youtubeInput)) {
        console.log(youtubeInput, "Valid");
        $(".youtube_validation_msg").text("해당 유튜브 링크가 적절한 포맷입니다.");
        $(".youtube_validation_msg").css({"color": "green"});
    } else {
        console.log(youtubeInput, "Invalid");
        $(".youtube_validation_msg").text("해당 유튜브 링크 포맷이 적절하지 않습니다.");
        $(".youtube_validation_msg").css({"color": "red"});
    };
  };
  $("#input_youtube").on("change", validateYoutubeLink);
  $(document).ready(function() {
    console.log("board_list raise");

    $("#newBoardBtn").on('click', function () {
      $("#newBoardForm")[0].reset();
      $(".form-group").hide();
      // 첫번째 선택 되도록
      $(".form-group").first().show();
      $("#selectInput option:eq(0)").prop("selected",true);
      $("#newBoardModal").modal("show");
    });
    $("#selectInput").on("change", function() {
      // var selectedValue = $(this).val();
      var selected = $(this).val();
      console.log(selected);
      $(".form-group:not(.input_" + selected).hide();
      $(".form-group:not(.input_" + selected+" .inputarea").children().val("");
      $("div."+selected).show();
      $(selected).show();
      console.log($(selected).children().val());
    });
    $("#newBoardForm").submit(function() {
      var inputFilled = false;
      $(".inputarea").each(function() {
        var inputVal = $.trim($(this).find("input, textarea").val());
        if (inputVal) { inputFilled = true; }
      });
      if (!inputFilled) {
        // alert('Please enter at least one input value.");
        return false;
      }
    });
    $(".closeBtn").on("click", function() {
      $("#newBoardModal").modal("hide");
      $("#newBoardForm")[0].reset();
      $(".form-group").hide();
      // 첫번째 선택 되도록
      $(".form-group").first().show();
      $("#selectInput option:eq(0)").prop("selected",true);
    });
    $('.form-control-file').change( function() {
      var this_val = $(this).val();
      if(window.FileReader){  // modern browser
        var filename = $(this)[0].files[0].name;
      }else {  // old IE
        var filename = $(this).val().split('/').pop().split('\\').pop();  // 파일명만 추출
      }
      $('.uploadchk').text(filename+' 파일 업로드 확인 되었습니다.')
    });
  });
</script>
<!-- E: board_list.html -->
{% endblock %}